# Build backend image
#   docker build -t wasaphoto-backend:latest -f Dockerfile.backend .
#
# Run the backend image
#   docker run -it -p 3000:3000 --rm wasaphoto-backend:latest

FROM golang:1.23.0 AS backend_builder
WORKDIR /src/
COPY . .
RUN go build -o /tmp/webapi ./cmd/webapi

FROM debian:stable
COPY --from=backend_builder /tmp/webapi /bin/webapi
EXPOSE 3000
CMD ["/bin/webapi"]